---
bases:
  - ../../bases/helmDefaults.yaml
  - ../../bases/environments.yaml.gotmpl

---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

---
releases:
  - name: fluentbit
    chart: prometheus-community/kube-prometheus-stack
    version: 75.3.0
    namespace: fluentbit
    values:
      - ./values.yaml
