---
bases:
  - ../../bases/helmDefaults.yaml
  - ../../bases/environments.yaml.gotmpl

---
repositories:
  - name: elastic
    url: https://helm.elastic.co

---
releases:
  - name: elastic-operator
    chart: prometheus-community/kube-prometheus-stack
    version: 75.3.0
    namespace: monitoring
    values:
      - ./values.yaml
