apiVersion: v1
kind: Pod
metadata:
  name: network-debug-pod
  namespace: default
spec:
  containers:
    - name: debug-tools
      image: nicolaka/netshoot:latest
      command: ["/bin/sh"]
      args: ["-c", "--login"]
      tty: true
      stdin: true
      securityContext:
        privileged: true # Required for certain tools
      volumeMounts:
        - name: host-proc
          mountPath: /host/proc
          readOnly: true
  volumes:
    - name: host-proc
      hostPath:
        path: /proc
