---
- name: Setup network for host
  ansible.builtin.import_tasks: network.yml
  tags:
    - common
    - network

- name: Ensuring user exists. User {{ app_user }}
  ansible.builtin.import_tasks: user.yml
  tags:
    - common
    - user

- name: Install pip and some useful package
  ansible.builtin.import_tasks: package.yml
  tags:
    - common
    - package
