---
- name: Create Docker group
  group:
    name: docker
    state: present

- name: Create user {{ app_user }}
  ansible.builtin.user:
    name: "{{ app_user }}"
    state: present
    shell: /bin/bash
    groups:
      - docker
    append: true
    update_password: always
    password: "{{ app_user_password }}"
