# Main playbook for bootstrap VM
---
- name: Setup environments for node
  hosts: all
  become: true
  roles:
    - common

- name: Setup docker for node
  hosts: all
  become: true
  roles:
    - docker

- name: Setup firewall for node
  hosts: all
  become: true
  roles:
    - ufw
