all:
  vars:
    ansible_user: itha_admin
    ansible_ssh_private_key_file: ~/.orbstack/ssh/id_ed25519
    app_user: itha_app
    app_user_password: ""
    app_base_dir: /home/itha_app
    hostname: "vm1"

  hosts:
    vm1:
      ansible_host: vm1@orb
