---
name: CI
"on":
  pull_request:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Yamllint
        uses: karancode/yamllint-github-action@master
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
