---
bases:
  - ../../bases/helmDefaults.yaml
  - ../../bases/environments.yaml.gotmpl

---
repositories:
  - name: elastic
    url: https://helm.elastic.co
  - name: fluent
    url: https://fluent.github.io/helm-charts

---
releases:
  - name: efk-elasticsearch
    chart: elastic/eck-elasticsearch
    createNamespace: true
    namespace: efk-stack
    version: 0.16.0-SNAPSHOT
    values:
      - ./elasticsearch/values.yaml

  - name: efk-kibana
    chart: elastic/eck-kibana
    createNamespace: true
    namespace: efk-stack
    version: 0.16.0-SNAPSHOT
    values:
      - ./kibana/values.yaml

  - name: efk-fluentbit
    chart: fluent/fluent-bit
    createNamespace: true
    namespace: efk-stack
    version: 0.49.1
    values:
      - ./fluentbit/values.yaml
