x-redis-common: &redis-common
  image: ${REDIS_IMAGE}
  command: /run.sh --appendonly yes --save "" --appendfsync no
  networks:
    - redis-net

x-sentinel-common: &sentinel-common
  image: ${SENTINEL_IMAGE}
  networks:
    - redis-net
  depends_on:
    redis-1:
      condition: service_healthy

services:
  # Initialize as Redis Master
  redis-1:
    <<: *redis-common
    container_name: redis-1
    volumes:
      - ./data/redis-1/:/bitnami/redis/data
      - ./logs/redis-1/:/opt/bitnami/redis/logs
    ports:
      - "6380:6380"
    environment:
      REDIS_PORT_NUMBER: 6380
      ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Initialize as Redis replica
  redis-2:
    <<: *redis-common
    container_name: redis-2
    volumes:
      - ./data/redis-2/:/bitnami/redis/data
      - ./logs/redis-2/:/opt/bitnami/redis/logs
    ports:
      - "6381:6381"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_PORT_NUMBER: 6381
      REDIS_MASTER_HOST: redis-1
      REDIS_MASTER_PORT_NUMBER: 6380
    depends_on:
      redis-1:
        condition: service_healthy

  # Initialize as Redis replica
  redis-3:
    <<: *redis-common
    container_name: redis-3
    volumes:
      - ./data/redis-3/:/bitnami/redis/data
      - ./logs/redis-3/:/opt/bitnami/redis/logs
    ports:
      - "6382:6382"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_PORT_NUMBER: 6382
      REDIS_MASTER_HOST: redis-1
      REDIS_MASTER_PORT_NUMBER: 6380
    depends_on:
      redis-1:
        condition: service_healthy

  sentinel-1:
    <<: *sentinel-common
    container_name: redis-sentinel-1
    volumes:
      - ./logs/sentinel-1/:/opt/bitnami/redis-sentinel/logs
    environment:
      REDIS_SENTINEL_PORT_NUMBER: 26380
      REDIS_SENTINEL_QUORUM: 2
      REDIS_MASTER_HOST: redis-1
      REDIS_MASTER_PORT_NUMBER: 6380
      REDIS_MASTER_SET: mymaster
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "26380:26380"

  sentinel-2:
    <<: *sentinel-common
    container_name: redis-sentinel-2
    volumes:
      - ./logs/sentinel-2/:/opt/bitnami/redis-sentinel/logs
    environment:
      REDIS_SENTINEL_PORT_NUMBER: 26381
      REDIS_SENTINEL_QUORUM: 2
      REDIS_MASTER_HOST: redis-1
      REDIS_MASTER_PORT_NUMBER: 6380
      REDIS_MASTER_SET: mymaster
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "26381:26381"

  sentinel-3:
    <<: *sentinel-common
    container_name: redis-sentinel-3
    volumes:
      - ./logs/sentinel-3/:/opt/bitnami/redis-sentinel/logs
    environment:
      REDIS_SENTINEL_PORT_NUMBER: 26382
      REDIS_SENTINEL_QUORUM: 2
      REDIS_MASTER_HOST: redis-1
      REDIS_MASTER_PORT_NUMBER: 6380
      REDIS_MASTER_SET: mymaster
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "26382:26382"

networks:
  redis-net:
    driver: bridge
